"use client";

import { useEffect,useState } from "react";
import Link from "next/link";
import { ArrowRight,Check,ChevronRight,Chrome,Globe2,Laptop,Languages,MessageCircle,MonitorSmartphone,Moon,Router,ShieldCheck,Smartphone,Sun,Users,Wifi } from "lucide-react";

type Lang="ru"|"en";type Theme="dark"|"light";
const copy={
  ru:{nav:["Возможности","Локации","Тарифы"],login:"Личный кабинет",badge:"Приватное подключение для всех устройств",title:"Свобода начинается",accent:"с подключения.",lead:"Arcanum объединяет быстрые локации, понятное управление и семейный доступ в одном защищённом пространстве.",bot:"Открыть Telegram-бота",plans:"Посмотреть тарифы",works:"Работает там, где удобно вам",soon:"Собственные приложения готовятся. Сейчас подключение доступно через проверенные клиенты и личный кабинет.",locations:"Быстрое соединение. Где бы вы ни были.",locationsText:"На старте — пять тщательно подобранных локаций с автоматическим контролем доступности. В дальнейшем сеть будет расширяться без смены вашей подписки.",featureLabel:"НЕ ПРОСТО ПОДКЛЮЧЕНИЕ",featureTitle:"Один аккаунт. Полный контроль.",features:[["Умный выбор маршрута","Кабинет показывает доступные локации и помогает выбрать оптимальное подключение."],["Приватность по умолчанию","DNS-запросы защищены, а сервис проектируется без хранения истории посещений."],["Все устройства","Телефон, компьютер, телевизор и роутер подключаются к одной подписке."],["Доступ для семьи","До пяти участников получают отдельные входы, сохраняя личную приватность."]],howLabel:"ПРОСТОЙ СТАРТ",howTitle:"От регистрации до защищённого соединения — три шага",steps:[["01","Войдите удобным способом","Telegram, Google и независимый Arcanum ID ведут в один профиль."],["02","Выберите формат","Для телефона, всех устройств или семейной группы."],["03","Подключитесь","Получите приложение, конфигурацию и понятную инструкцию."]],priceLabel:"ТАРИФЫ",priceTitle:"Без скрытых условий",month:"/ месяц",choose:"Выбрать",popular:"ПОПУЛЯРНЫЙ",familyTitle:"Одна подписка. Своя приватность у каждого.",familyText:"Добавляйте близких по защищённой ссылке. У каждого будет собственный вход, а оплачивать общий тариф сможет любой участник.",familyButton:"Подключить семью",cta:"Ваше пространство в интернете уже готово.",ctaText:"Начните с Telegram — настройка займёт несколько минут.",footer:"Сервис находится в разработке.",plansData:[["Мобильный","199 ₽","До 2 устройств",["Телефон и планшет","Все доступные локации","Поддержка в Telegram"]],["Личный","299 ₽","До 5 устройств",["Телефон, компьютер и ТВ","Все доступные локации","Приоритетная поддержка"]],["Семейный","449 ₽","5 участников · 15 устройств",["Личные профили","Общий баланс","Приглашение по ссылке"]]]},
  en:{nav:["Features","Locations","Plans"],login:"Dashboard",badge:"Private connection for every device",title:"Freedom begins",accent:"with a connection.",lead:"Arcanum brings fast locations, clear controls and family access into one protected space.",bot:"Open Telegram bot",plans:"View plans",works:"Works wherever you need it",soon:"Native apps are on the way. For now, connect through trusted clients and your personal dashboard.",locations:"Fast connection. Wherever you are.",locationsText:"We are launching with five carefully selected locations and automatic availability checks. The network will grow without requiring a new subscription.",featureLabel:"MORE THAN A CONNECTION",featureTitle:"One account. Complete control.",features:[["Smart routing","Your dashboard shows available locations and helps you choose the optimal connection."],["Private by default","DNS requests are protected and the service is designed without browsing history storage."],["Every device","Connect your phone, computer, TV and router under one subscription."],["Made for families","Up to five members get separate access while keeping their activity private."]],howLabel:"QUICK START",howTitle:"From signup to a protected connection in three steps",steps:[["01","Choose how to sign in","Telegram, Google and an independent Arcanum ID lead to one profile."],["02","Pick your plan","For mobile, all devices or the whole family."],["03","Get connected","Receive the client, configuration and a clear guide."]],priceLabel:"PLANS",priceTitle:"Simple pricing, no surprises",month:"/ month",choose:"Choose plan",popular:"POPULAR",familyTitle:"One subscription. Personal privacy for everyone.",familyText:"Invite family through a secure link. Everyone gets a separate login, while any member can contribute to the shared plan.",familyButton:"Protect your family",cta:"Your private space online is ready.",ctaText:"Start in Telegram — setup only takes a few minutes.",footer:"The service is currently in development.",plansData:[["Mobile","₽199","Up to 2 devices",["Phone and tablet","Every available location","Telegram support"]],["Personal","₽299","Up to 5 devices",["Phone, computer and TV","Every available location","Priority support"]],["Family","₽449","5 members · 15 devices",["Personal profiles","Shared balance","Invite by secure link"]]]}
};
const platforms=[[Smartphone,"iOS / Android"],[Laptop,"Windows / macOS"],[Router,"Routers"],[Chrome,"Browser"],[MonitorSmartphone,"Android TV"]] as const;
const countries=[["🇫🇮","Finland"],["🇳🇱","Netherlands"],["🇩🇪","Germany"],["🇰🇿","Kazakhstan"],["🇦🇲","Armenia"]];

export default function HomeClient(){
  const[lang,setLang]=useState<Lang>("ru");const[theme,setTheme]=useState<Theme>("dark");const t=copy[lang];
  useEffect(()=>{const saved=(localStorage.getItem("arcanum-theme") as Theme|null);const initial=saved||((matchMedia("(prefers-color-scheme: light)").matches)?"light":"dark");setTheme(initial);document.documentElement.dataset.theme=initial;const savedLang=localStorage.getItem("arcanum-lang") as Lang|null;if(savedLang)setLang(savedLang)},[]);
  const changeTheme=()=>{const next=theme==="dark"?"light":"dark";setTheme(next);document.documentElement.dataset.theme=next;localStorage.setItem("arcanum-theme",next)};
  const changeLang=()=>{const next=lang==="ru"?"en":"ru";setLang(next);localStorage.setItem("arcanum-lang",next);document.documentElement.lang=next};
  return <main className="landing">
    <header className="siteNav shell"><Link className="brand" href="/">ARCANUM<span>NOX</span></Link><nav>{t.nav.map((item,i)=><a key={item} href={["#features","#locations","#plans"][i]}>{item}</a>)}</nav><div className="navActions"><button className="iconButton" onClick={changeTheme} aria-label="Toggle theme">{theme==="dark"?<Sun/>:<Moon/>}</button><button className="langButton" onClick={changeLang}><Languages/>{lang.toUpperCase()}</button><Link className="button navLogin" href="/login">{t.login}</Link></div></header>
    <section className="newHero"><video autoPlay muted loop playsInline aria-hidden="true"><source src="https://cdn.pixabay.com/video/2020/05/25/40130-424930941_large.mp4" type="video/mp4"/></video><div className="heroVeil"/><div className="heroNoise"/><div className="heroLayout shell"><div className="heroCopy"><span className="eyebrow"><ShieldCheck/>{t.badge}</span><h1>{t.title}<br/><em>{t.accent}</em></h1><p>{t.lead}</p><div className="actions"><a className="button primary" href="https://t.me/arcanumvpnbot">{t.bot}<ArrowRight/></a><a className="button secondary" href="#plans">{t.plans}</a></div><div className="trustRow"><span><Wifi/>5 locations</span><span><ShieldCheck/>Private by design</span><span><Users/>Family access</span></div></div><div className="portal" aria-hidden="true"><div className="portalRing ringOne"/><div className="portalRing ringTwo"/><div className="portalCore"><Globe2/></div><span className="node nodeOne">FI</span><span className="node nodeTwo">NL</span><span className="node nodeThree">KZ</span></div></div></section>
    <section className="platformSection shell"><div className="sectionHead compact"><span>{t.works}</span><p>{t.soon}</p></div><div className="platformGrid">{platforms.map(([Icon,name])=><article key={name}><Icon/><strong>{name}</strong><small>Arcanum Connect</small><ChevronRight/></article>)}</div></section>
    <section className="locationSection" id="locations"><div className="shell locationCopy"><span>GLOBAL NETWORK</span><h2>{t.locations}</h2><p>{t.locationsText}</p></div><div className="countryMarquee"><div>{[...countries,...countries].map(([flag,name],i)=><span key={`${name}-${i}`}><b>{flag}</b>{name}<i>24 ms</i></span>)}</div></div></section>
    <section className="section shell" id="features"><div className="sectionHead"><span>{t.featureLabel}</span><h2>{t.featureTitle}</h2></div><div className="bentoGrid">{t.features.map((item,i)=><article className={`bento bento${i+1}`} key={item[0]}><span>{String(i+1).padStart(2,"0")}</span>{i===0?<Globe2/>:i===1?<ShieldCheck/>:i===2?<MonitorSmartphone/>:<Users/>}<h3>{item[0]}</h3><p>{item[1]}</p><div className="cardGlow"/></article>)}</div></section>
    <section className="section shell howSection"><div className="sectionHead"><span>{t.howLabel}</span><h2>{t.howTitle}</h2></div><div className="stepLine">{t.steps.map(step=><article key={step[0]}><b>{step[0]}</b><div><h3>{step[1]}</h3><p>{step[2]}</p></div></article>)}</div></section>
    <section className="section shell" id="plans"><div className="sectionHead"><span>{t.priceLabel}</span><h2>{t.priceTitle}</h2></div><div className="planGrid">{t.plansData.map((plan,i)=><article className={i===1?"plan featured":"plan"} key={plan[0] as string}>{i===1&&<small>{t.popular}</small>}<h3>{plan[0] as string}</h3><p className="price">{plan[1] as string}<span>{t.month}</span></p><p>{plan[2] as string}</p><ul>{(plan[3] as string[]).map(item=><li key={item}><Check/>{item}</li>)}</ul><a className="button primary" href="https://t.me/arcanumvpnbot">{t.choose}</a></article>)}</div></section>
    <section className="familyBanner shell"><div className="familyVisual"><div><Users/></div><span/><span/><span/></div><div><span>ARCANUM FAMILY</span><h2>{t.familyTitle}</h2><p>{t.familyText}</p><a className="button secondary" href="https://t.me/arcanumvpnbot">{t.familyButton}<ArrowRight/></a></div></section>
    <section className="finalCta shell"><MessageCircle/><h2>{t.cta}</h2><p>{t.ctaText}</p><a className="button primary" href="https://t.me/arcanumvpnbot">{t.bot}<ArrowRight/></a></section>
    <footer className="shell"><span className="brand">ARCANUM<span>NOX</span></span><p>© 2026 Arcanum. {t.footer}</p><div><a href="https://t.me/arcanumvpnbot">Telegram</a><Link href="/login">{t.login}</Link></div></footer>
  </main>
}
