import type { ReactNode } from "react";
import Link from "next/link";
import { CalendarDays, Check, Copy, CreditCard, KeyRound, Laptop, Mail, MessageCircle, ShieldCheck, UserPlus, Users } from "lucide-react";
import { redirect } from "next/navigation";
import { currentUser } from "@/lib/auth";
import { supabaseAdmin } from "@/lib/supabase-admin";
import "./dashboard.css";
import { Preferences } from "@/app/preferences";

type User = { id:string;first_name:string|null;telegram_id:number|null;telegram_username:string|null;google_id:string|null;email:string|null;referral_code:string;access_id:string|null };

export default async function Dashboard() {
  const rawUser=await currentUser();if(!rawUser)redirect("/login");const user=rawUser as unknown as User;const db=supabaseAdmin();const now=new Date().toISOString();
  const [{data:subscription},{count:devices},{data:membership}]=await Promise.all([db.from("subscriptions").select("status,expires_at,plans(name,device_limit,family_limit)").eq("user_id",user.id).eq("status","active").gt("expires_at",now).order("expires_at",{ascending:false}).limit(1).maybeSingle(),db.from("devices").select("id",{count:"exact",head:true}).eq("user_id",user.id).eq("status","active"),db.from("family_members").select("role,families(id,owner_id)").eq("user_id",user.id).maybeSingle()]);
  const plan=subscription?.plans as unknown as {name?:string;device_limit?:number}|null;const referralUrl=`https://t.me/${process.env.NEXT_PUBLIC_TELEGRAM_BOT_USERNAME||"arcanumvpnbot"}?start=ref_${user.referral_code}`;const expires=subscription?.expires_at?new Intl.DateTimeFormat("ru-RU",{day:"numeric",month:"long",year:"numeric"}).format(new Date(subscription.expires_at)):null;
  return <main className="dashboard">
    <header><Link className="brand" href="/">ARCANUM <span>NOX</span></Link><div className="dashActions"><Preferences/><form action="/api/auth/logout" method="post"><button className="button ghost">Выйти</button></form></div></header>
    <section className="dashHero"><span>ЛИЧНЫЙ КАБИНЕТ</span><h1>Здравствуйте, {user.first_name||"пользователь"}</h1><p>{user.telegram_username?`@${user.telegram_username}`:user.email||"Аккаунт Arcanum"}</p></section>
    <section className="statusGrid"><article className={subscription?"statusCard active":"statusCard"}><ShieldCheck/><div><small>ПОДПИСКА</small><h2>{plan?.name||"Не активна"}</h2><p>{expires?<>Действует до {expires}</>:"Выберите тариф, чтобы получить доступ"}</p></div></article><article className="statusCard"><Laptop/><div><small>УСТРОЙСТВА</small><h2>{devices||0} подключено</h2><p>{plan?.device_limit?`Доступно до ${plan.device_limit}`:"Лимит появится после активации"}</p></div></article></section>
    <section className="dashColumns"><article className="panel"><div className="panelTitle"><CreditCard/><div><small>УПРАВЛЕНИЕ</small><h2>Тариф и оплата</h2></div></div>{subscription?<><p>Продление добавит месяц к текущему сроку подписки.</p><button className="button primary" disabled>Продлить — скоро</button></>:<><p>Оплата картой и через СБП появится после подключения платёжного провайдера.</p><Link className="button primary" href="/#plans">Выбрать тариф</Link></>}</article><article className="panel"><div className="panelTitle"><Users/><div><small>СЕМЬЯ</small><h2>{membership?"Семейная группа":"Подключите близких"}</h2></div></div><p>{membership?"Вы состоите в семейной группе. Управление участниками появится после активации семейного тарифа.":"На семейном тарифе можно добавить до пяти участников по защищённой ссылке."}</p><button className="button ghost" disabled><UserPlus size={17}/> Приглашения — скоро</button></article></section>
    <section className="accountsPanel"><div className="accountsIntro"><small>БЕЗОПАСНОСТЬ</small><h2>Способы входа</h2><p>Привяжите несколько способов. Подписка, устройства и семья останутся в одном профиле.</p></div><div className="accountMethods"><AccountMethod icon={<MessageCircle/>} name="Telegram" detail={user.telegram_username?`@${user.telegram_username}`:"Вход через Telegram"} linked={Boolean(user.telegram_id)} href="/api/auth/telegram/link"/><AccountMethod icon={<Mail/>} name="Google" detail={user.google_id?user.email||"Google подключён":"Gmail и Google ID"} linked={Boolean(user.google_id)} href="/api/auth/google?mode=link"/></div></section>
    <section className="accessPanel"><div><small>НЕЗАВИСИМЫЙ ВХОД</small><h2><KeyRound/> Arcanum ID</h2><p>Входите без Google и Telegram. Секретная фраза хранится только как стойкий хеш.</p></div><form action="/api/account/access" method="post"><label>Arcanum ID<input name="accessId" defaultValue={user.access_id||""} minLength={5} maxLength={32} pattern="[a-z0-9][a-z0-9_-]{4,31}" placeholder="например, noctis_27" required/></label><label>Новая секретная фраза<input name="password" type="password" minLength={12} maxLength={128} autoComplete="new-password" placeholder="не менее 12 символов" required/></label><button className="button primary">{user.access_id?"Обновить данные":"Создать независимый вход"}</button></form></section>
    <section className="referral"><div><small>РЕФЕРАЛЬНАЯ ПРОГРАММА</small><h2>Приглашайте друзей</h2><p>Персональная ссылка уже создана. Правила начисления бонусов будут включены перед запуском оплаты.</p></div><div className="referralCode"><code>{referralUrl}</code><Copy size={18}/></div></section>
    <footer className="dashFooter"><CalendarDays size={17}/><span>История операций и уведомления появятся после подключения платежей.</span></footer>
  </main>;
}

function AccountMethod({icon,name,detail,linked,href}:{icon:ReactNode;name:string;detail:string;linked:boolean;href:string}){return <div className="accountMethod"><span className="accountIcon">{icon}</span><div><strong>{name}</strong><small>{detail}</small></div>{linked?<span className="linkedBadge"><Check size={15}/> Привязан</span>:<a className="button ghost" href={href}>Привязать</a>}</div>}
